### ISSUE TITLE
logging.logger_setup supporting only environment variables for json logger

### ISSUE THREAD

**Issue by nischalhp** [omni-us/reconplogger#2]
As we support plain logger and null handler out of the box, I think we should also support JSON logger without having to set environment variables with a method to use JSON logger, or taking the arguments to support either environment variables or variables passed to the method.

@mauvilsa your thoughts on the same?

**Comment by mauvilsa** [comment]
@nischalhp I am not sure if I completely understand your proposal. Currently if environment variables are unset, then by default the plain logger is used. From what you say I don't think you mean changing the default to be the json logger. Giving the option to the developers to override the use of the environment variables means that they could end up developing a service in which the logging can't be changed from the outside, e.g. via helm.

One possibility I can think of is that logger_setup receives an optional argument to indicate what to do if the environment variables are not set, e.g. `default_if_env_unset`. If not provided, the current behavior would continue. Otherwise, it could be set to a string, e.g. default_if_env_unset='json_logger' which would take a logger from the config, or even directly give a logger object to use.

**Comment by nischalhp** [comment]
@mauvilsa That is definitely one way we can do. What I am suggesting is, in the ```logging.logger_setup``` one can pass arguments if environment variables are not set i.e if I pass ```logging.logger_setup('reconplogger_default', 'json_logger') ``` then I should get a json logger back, not the default one even though I have not set the environment variables.

**Comment by mauvilsa** [comment]
The problem that I see with that is that it opens up a way to use reconplogger in a way which makes logger not reconfigurable from the outside. So I would argue against this. Though the possibility that I was suggesting looks similar, but still preserves the reconfigurability. The signature of the function could be, `def logger_setup(default_logger='plain_logger', env_prefix='LOGGER' init_messages=False):`. The normal way to use it would be simply `logger = logger_setup()`. If someone wants to have as default the json logger, then it could be called as `logger = logger_setup('json_logger')` or being more explicit about what is going on `logger = logger_setup(default_logger='json_logger')`. If there are multiple apps running in the same system for which the logging should be configurable independently for both, then each app would initialize as `logger = logger_setup(env_prefix='LOGGER_APP1')` or `logger = logger_setup(env_prefix='LOGGER_APP2')`.

**Comment by nischalhp** [comment]
Definitely makes sense @mauvilsa, I shall create a branch and add this.

**Comment by nischalhp** [comment]
@mauvilsa 

So I was looking into the code and I think the method definition should be this:

```def logger_setup(logger_name='plain_logger', env_cfg=None, init_messages=False')``` 

The reason is that we can load the cfg if required via dictionary or path to a file as already support by the method and can also pass the logger name required if different from default as present in the cfg. Let me know what you think.

**Comment by nischalhp** [comment]
Have created a branch with change for the same : https://github.com/omni-us/reconplogger/tree/feature/logger_setup

**Comment by nischalhp** [comment]
This issue has been resolved with this commit : https://github.com/omni-us/reconplogger/commit/a6ab1bb0b36e1a199506832a4047c539da069d35
